### ISSUE TITLE
Nuget error

### ISSUE THREAD

**Issue by jandnil** [InSciCo/LazyStack#5]
Hi!

I'm receiving an error generating your tutorial project: Please Move any NugetPackageVersions 'you added (if any)' to the new ProjectOptions.NugetPackageVersion and delete the old NugetPackageVersions. 

Updated Nuget packages using VS as usual , but where should i change the above mentioned reference?

Many thanks in advance

**Comment by tmay57** [comment]
@jandnil 
I apologize for the late response. Our GitHub notifications failed for some reason.
Please let me know if you still have this issue.

**Comment by jandnil** [comment]
Hi! 
Sorry for the delay I can confirm that I still encounter the same error:
![image](https://user-images.githubusercontent.com/25294961/129475722-c8fdb78b-6663-4058-8d76-177b46d8fdc1.png)
If generating AWSsettings.json gives you this issue from your logs:
![image](https://user-images.githubusercontent.com/25294961/129475815-fddbfa26-aa72-4465-b8fb-3afdb6e5a5aa.png)
Is there anything i can doo to assist in investigating and resolving this issue?
Best regards Anders

**Comment by tmay57** [comment]
@jandnil 
It looks like you are doing the Visual Studio Windows tutorial.
Please confirm which step you are on in the tutorial. 
2.3.3
5.5.4
6.2.1

**Comment by jandnil** [comment]
Its correct its the VS  Windows tutorial
Step 5.1.4 gives first error , second one is from step 6.2.1

**Comment by tmay57** [comment]
@jandnil
OK. Please send me the LazyStack.yaml file.

**Comment by jandnil** [comment]
Here it is. Best regards Anders

**Comment by tmay57** [comment]
@jandnil 
Sorry - that didn't work. To attach the files, please add a .txt extension to each and then just drag and drop them into the area at the bottom of the comment box.

**Comment by jandnil** [comment]
[LazyStack.yaml.txt](https://github.com/InSciCo/LazyStack/files/6988572/LazyStack.yaml.txt)
Hopefully this works ;-)

**Comment by tmay57** [comment]
@jandnil 
Yes - that did indeed work. I'll do a little triage on this end and get back to you shortly.

**Comment by tmay57** [comment]
OK - Somehow your LazyStack.yaml is of the old style. Using the link in step 5.1.1 Please download the LazyStack.yaml file again. Check if the first line of the file reads:
```
LazyStackDirectivesVersion: 1.1.0
```
If it doesn't, please clear the cache for the site and try again. I just check the download on my side and it does return the correct file.

Once you have a correct LazyStack.yaml file you can regenerate the projects and go on to Step 6 (Publish to AWS). After publishing your stack to AWS you can generate the AwsSettings.json file.

**Comment by jandnil** [comment]
Hi! 
That resolved the issue and the explanation is that i used the petstore repo yaml-file (https://github.com/InSciCo/LazyStackTutorial/tree/main/PetStore) that one is then in the old style and hence it doesn't work . After changing to new style everything went smooth. Thanks for the clarification and assistance. HAve a nice day and thanks for your contributions!

**Comment by tmay57** [comment]
@jandnil 
I'm glad the rest of the tutorial went smoothly for you. We'd love to hear if you end up using LazyStack to help build a system. 
Cheers,
Tim
